#!/usr/bin/env python3
"""workflow.json -> a per-workflow main.cpp. Loads the SAME testdata JSON
ws_cur uses, converts it into this pair's InRecord/Config (only the fields
gen_types.py declared), calls the generated function, and checks the result
against expected_events. The model never sees this file.
"""
import pathlib, sys
import gen_types

# raw detection JSON -> one InRecord field. Every field the registry can
# name; gen_types.py only ever wires up the ones a given pair declares.
DETECTION_GETTERS = {
    "bbox":       '{ auto b = jd.value("bbox", Json::array({0,0,0,0})); r.bbox = { b[0].get<float>(), b[1].get<float>(), b[2].get<float>(), b[3].get<float>() }; }',
    "class_id":   'r.class_id = jd.value("class_id", 0);',
    "confidence": 'r.confidence = jd.value("confidence", 0.0f);',
    "label":      'r.label = jd.value("label", std::string());',
    "track_id":   'r.track_id = jd.value("track_id", -1);',
}

# frame-level (not per-detection) context fields, read once per frame.
FRAME_CTX_GETTERS = {
    "timestamp_us": 'fd.timestamp_us = jf.value("timestamp_us", (int64_t)0);',
    "camera_id":    'fd.camera_id = jf.value("camera_id", std::string("cam_01"));',
}

PARAM_GETTERS = {
    "int":    lambda name: f'c.{name} = j.value("{name}", 0);',
    "float":  lambda name: f'c.{name} = j.value("{name}", 0.0f);',
    "Point2f": lambda name: (
        f'if (j.contains("{name}")) {{ c.{name}.x = j["{name}"][0].get<float>(); '
        f'c.{name}.y = j["{name}"][1].get<float>(); }}'),
}


def build(wf_path, out_path):
    info = gen_types.build(wf_path)
    in_fields = info["in_fields"]
    params = info["param_fields"]
    frames = info["frames"]
    fn_name = info["fn_name"]
    ctx_fields = info["frame_ctx_fields"]

    to_record_body = "\n    ".join(DETECTION_GETTERS[f] for f in in_fields)

    ctx_struct_fields = "\n    ".join(
        f"{gen_types.FIELD_CPP[f][0]} {f};" for f in ctx_fields)
    ctx_load_body = "\n        ".join(FRAME_CTX_GETTERS[f] for f in ctx_fields)

    param_lines = []
    for name, t in params.items():
        t = gen_types._param_type(t)
        getter = PARAM_GETTERS.get(t)
        if getter is None:
            raise gen_types.UnsupportedEdge(f"no JSON loader for param type {t}")
        param_lines.append(getter(name))
    config_body = "\n    ".join(param_lines)

    frame_loop = _frame_loop(frames, fn_name, ctx_fields)

    src = f'''// GENERATED by gen_harness.py from {pathlib.Path(wf_path).name}. Do not hand-edit.
#include "types.hpp"
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <string>
#include <vector>
#include "nlohmann/json.hpp"

using Json = nlohmann::json;

void {fn_name}({_decl_args(frames, ctx_fields)}const Config &cfg, std::vector<OutRecord> &out);

struct FrameData {{
    std::vector<InRecord> records;
    {ctx_struct_fields if ctx_struct_fields else "// no frame-level context fields needed"}
}};

static InRecord toRecord(const Json &jd)
{{
    InRecord r;
    {to_record_body if to_record_body else "(void)jd;"}
    return r;
}}

static Config loadConfig(const Json &j)
{{
    Config c;
    {config_body if config_body else "(void)j;"}
    return c;
}}

static std::vector<FrameData> loadFrames(const Json &root)
{{
    std::vector<FrameData> frames;
    for (const auto &jf : root.value("frames", Json::array()))
    {{
        FrameData fd;
        {ctx_load_body if ctx_load_body else "(void)jf;"}
        for (const auto &jd : jf.value("detections", Json::array()))
            fd.records.push_back(toRecord(jd));
        frames.push_back(fd);
    }}
    return frames;
}}

int main(int argc, char **argv)
{{
    const std::string fp = (argc > 1) ? argv[1] : "frames.json";
    const std::string cp = (argc > 2) ? argv[2] : "config.json";

    std::ifstream ff(fp), cf(cp);
    if (!ff.is_open()) {{ std::printf("cannot open %s\\n", fp.c_str()); return 2; }}
    if (!cf.is_open()) {{ std::printf("cannot open %s\\n", cp.c_str()); return 2; }}
    Json froot; ff >> froot;
    Json croot; cf >> croot;

    auto frames = loadFrames(froot);
    Config cfg = loadConfig(croot);
    if (frames.empty()) {{ std::printf("no frames from %s\\n", fp.c_str()); return 2; }}

    int total = 0;
{frame_loop}
    std::printf("\\ntotal events: %d\\n", total);
    if (croot.contains("expected_events"))
    {{
        int expected = croot.value("expected_events", 0);
        std::printf("expected    : %d\\n", expected);
        if (total == expected) {{ std::printf("\\nPASS\\n"); return 0; }}
        std::printf("\\nFAIL - compiles but behaviour is wrong\\n"); return 1;
    }}
    return 0;
}}
'''
    pathlib.Path(out_path).write_text(src)


def _decl_args(frames, ctx_fields):
    ctx = "".join(f", {gen_types.FIELD_CPP[f][0]} {f}" if gen_types.FIELD_CPP[f][0] != "std::string"
                  else f", const std::string &{f}" for f in ctx_fields)
    if frames == "2":
        return f"const std::vector<InRecord> &prev, const std::vector<InRecord> &curr{ctx}, "
    return f"const std::vector<InRecord> &curr{ctx}, "


def _frame_loop(frames, fn_name, ctx_fields):
    ctx_args = "".join(f", frames[i].{f}" for f in ctx_fields)
    if frames == "2":
        return f'''    for (size_t i = 1; i < frames.size(); ++i)
    {{
        std::vector<OutRecord> out;
        {fn_name}(frames[i-1].records, frames[i].records{ctx_args}, cfg, out);
        std::printf("frame %2zu  det=%2zu  events=%zu%s\\n", i, frames[i].records.size(),
                    out.size(), out.empty() ? "" : "   <-- FIRED");
        total += (int)out.size();
    }}'''
    return f'''    for (size_t i = 0; i < frames.size(); ++i)
    {{
        std::vector<OutRecord> out;
        {fn_name}(frames[i].records{ctx_args}, cfg, out);
        std::printf("frame %2zu  det=%2zu  events=%zu%s\\n", i, frames[i].records.size(),
                    out.size(), out.empty() ? "" : "   <-- FIRED");
        total += (int)out.size();
    }}'''


if __name__ == "__main__":
    build(sys.argv[1], sys.argv[2])
